name: ProxyBlockXYZSpigot
authors: [Timeox2k, HorizonCode]
version: 1.2
main: xyz.proxyblock.spigot.ProxyBlockXYZ

commands:
  proxyblock:
    description: The Main command for the ProxyBlock Plugin
    aliases:
      - pb